export const feList = [
  {
    name: "HTML",
    percent: 80,
  },
  {
    name: "CSS",
    percent: 70,
  },
  {
    name: "JavaScript",
    percent: 80,
  },
  {
    name: "React",
    percent: 80,
  },
];

export const designList = [
  {
    name: "Figma",
    percent: 50,
  },
];

export const projectList = [
  {
    id: 1,
    title: "CV Creator",
    imgPath: "/work/img1.jpg",
    description:
      "An online CV creator using gatsby framework, context api and css. User key in their informations and it will auto generate a CV with a default template. User have an option to save or download the created CV.",
  },
  {
    id: 2,
    title: "Huddle Landing Page",
    imgPath: "/work/img2.jpg",
    description:
      "A project using pure HTML and CSS. This project is from FrontEnd Mentor website challenge.",
  },
  {
    id: 3,
    title: "Base Apparel Coming Soon",
    imgPath: "/work/img3.jpg",
    description:
      "A project using pure HTML, CSS and javascript. Using a simple javascript function to validate form when submitted.",
  },
  {
    id: 4,
    title: "Four Card Feature",
    imgPath: "/work/img4.jpg",
    description:
      "A project using pure HTML, CSS. This project is from FrontEnd Mentor website challenge.",
  },
  {
    id: 5,
    title: "Futurama Wiki Page",
    imgPath: "/work/img5.jpg",
    description:
      "A simple wikipedia site for Futurama fans. This project using Nextjs framework, fetch api and css. futurama data is fetch from external api and the page for each character is generated by using dynamics link.",
  },
  {
    id: 6,
    title: "Travel Blog",
    imgPath: "/work/img6.jpg",
    description:
      "A project using Nextjs framework, tailwinds css and Dato CMS. All the data is fetch from Dato CMS using graphql.",
  },
  {
    id: 7,
    title: "Conference Schedule Site",
    imgPath: "/work/img7.jpg",
    description:
      "A project using react js, tailwinds css, leaflet and md files. the data is fetch from md files and json files. There is a map of the site location created using leaflet map.",
  },
  {
    id: 8,
    title: "QS-ISKB Daily Response",
    imgPath: "/work/img8.jpg",
    description:
      "A dashboard project using Nextjs framework, react-table, css, google api. The data is fetch from google sheet api. Using server side rendering, data is automatically load when site refreshed.",
  },
];
